### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous.

### ISSUE THREAD

**Issue by Pranavesh-Panakkal** [danielbwright/RainyDay#1]
**File**: RainyDay_Py3.py
**Line**: 1223 (if rainmax>=catmax[checkind]:)

**Steps to recreate the error:**
Run Madison_example.sst  (no changes to the file from GitHub except MINPATH, RAINPATH, and CREATECATALOG)

**Context**: Processing file 2693 out of 5122 (53%): StageIV_FilledCorr.20130405.03degree.nc
```
if rainmax>tempmin:
    checksep=intime[k]-cattime[:,-1] # Array of length 400
    if (checksep<timeseparation).any():
        checkind=np.where(checksep<timeseparation) # Returns [6.484375 1.5]
        if rainmax>=catmax[checkind]: # 1.5 >= [6.484375 1.5] (shall I use any()?)
            catmax[checkind]=rainmax # Note `checkind` is an array
            cattime[checkind,:]=subtime
```

I'm unable to recreate the error using the old StageIV data you shared (ST4.*.newregridded.nc).

**Comment by danielbwright** [comment]
That's a surprising problem, since by design there should never be more than one value for checkind. However, we've found some weird behavior that might be related (not creating an error though). Have you tried the newer stage IV data? It should be superior. If this is a serious issue for you, I can look closer, but my team is currently doing a major refactoring of RainyDay so I am hesitant to invest a lot of time fixing bugs.

**Comment by Pranavesh-Panakkal** [comment]
Hi Daniel, thanks for the prompt response. Yes, I have tried with both new and old stage IV data. The reported error will happen if only I use the latest Stage IV data (StageIV_FilledCorr.20130405.03degree.nc); I have been using the old Stage IV data (ST4.*.newregridded.nc) without any errors. 

I will continue to work with the old Stage IV data and will also try to understand more about the code structure from my end. Thanks for sharing your work.

**Comment by danielbwright** [comment]
Sounds good. I’m traveling this week but I’m happy to discuss when I’m back stateside. I like to see folks using the software (especially using it well!).
Dan

--
Daniel B. Wright (he/him/his)
Associate Professor, Civil and Environmental Engineering
University of Wisconsin-Madison
Hydroclimate Extremes Research Group (https://her.cee.wisc.edu/)

Visiting Scientist, Office of Water Prediction
National Oceanic and Atmospheric Administration




From: Pranavesh Panakkal ***@***.***>
Date: Tuesday, May 16, 2023 at 4:50 PM
To: danielbwright/RainyDay ***@***.***>
Cc: Daniel Wright ***@***.***>, Comment ***@***.***>
Subject: Re: [danielbwright/RainyDay] ValueError: The truth value of an array with more than one element is ambiguous. (Issue #1)

Hi Daniel, thanks for the prompt response. Yes, I have tried with both new and old stage IV data. The reported error will happen if only I use the latest Stage IV data (StageIV_FilledCorr.20130405.03degree.nc); I have been using the old Stage IV data (ST4.*.newregridded.nc) without any errors.

I will continue to work with the old Stage IV data and will also try to understand more about the code structure from my end. Thanks for sharing your work.

**Comment by danielbwright** [comment]
Could you please somehow share with me a reproducible example of this issue? That means at least your .sst file, and any shapefiles (if any) that you are using. Thanks!

**Comment by danielbwright** [comment]
I wasn't able to create an error. However, I'm hitting a local version of RainyDay_functions.py, which might explain that. Could you share the full error message? If the error is within a function from that file, then I'll know that I need to go deeper!

**Comment by Pranavesh-Panakkal** [comment]
Hi Daniel,  I'm able to recreate the error starting from scratch (i.e., downloading the current version of RainyDay from Github and Stage IV data from https://drive.google.com/drive/folders/1g6_Cvxnr4IGqqzDrKWv9YquUG5_pZINK). 

Full error message:
```
Processing file 2692 out of 5122 (53%): StageIV_FilledCorr.20130405.03degree.nc
Reading an older-style NetCDF file
Processing file 2693 out of 5122 (53%): StageIV_FilledCorr.20130405.03degree.nc
Traceback (most recent call last):
  File "/Users/pranavesh/Downloads/RainyDay-master/Source/RainyDay_Py3.py", line 1224, in <module>
    if rainmax>=catmax[checkind]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Variable values causing the error:
```
if rainmax>tempmin:
    checksep=intime[k]-cattime[:,-1]                                   # length 400
    if (checksep<timeseparation).any():                              # timeseparation = 4320
        checkind=np.where(checksep<timeseparation)                     # Returns [6.484375 1.5]; checkind = [367 368]
        if rainmax>=catmax[checkind]:                                  # 1.5 >= [6.484375 1.5]
            catmax[checkind]=rainmax                                   # Note `checkind` is an array
            cattime[checkind,:]=subtime
```

Typically, `checkind` is a single value. But, in this case, `checkind` is assigned a tuple with two values; this might be the source of this error.

**Comment by Pranavesh-Panakkal** [comment]
Hello, Daniele. I identified the issue. The problem is with the dataset; the `2011` Stage IV data folder on the shared Google Drive has `2013`'s files (the `2011` data folder contains 730 files instead of 365). For instance, the file `StageIV_FilledCorr.20130405.03degree.nc` can be found in the `2013` and `2011` folders.  I removed the 2013 files from the `2011` folder, and the model now runs flawlessly. Thanks for your willingness to help.

**Comment by danielbwright** [comment]
Ok, thanks for letting me know.



From: Pranavesh Panakkal ***@***.***>
Date: Tuesday, May 23, 2023 at 12:35 AM
To: danielbwright/RainyDay ***@***.***>
Cc: Daniel Wright ***@***.***>, Comment ***@***.***>
Subject: Re: [danielbwright/RainyDay] ValueError: The truth value of an array with more than one element is ambiguous. (Issue #1)

Hello, Daniele. I identified the issue. The problem is with the dataset; the 2011 Stage IV data folder on the shared Google Drive has 2013's files (the 2011 data folder contains 730 files instead of 365). For instance, the file StageIV_FilledCorr.20130405.03degree.nc can be found in the 2013 and 2011 folders. I removed the 2013 files from the 2011 folder, and the model now runs flawlessly. Thanks for your willingness to help.
